# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d23c9a74410d566ab046f1ff6d276358f4e5d44337f25a97c5ae0d1ae2076378365cf13ffd547a197c849a4fcf0d0d7365ced23e099ece668c6354e52421a82

test:
  secret_key_base: 7761e6305d78210bf5ac96919b3280df19301a803ec8eaf1fe9bca70a7ecd0e047491136409ec81eb7894ee0447153de0714293b300a3ae6d0578305e92e25a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
